### ISSUE TITLE
Any love for lower version of CMake?

### ISSUE THREAD

**Issue by abrahamdsl** [vusec/ridl#12]
My server is quite not recent.. can be only installed up to 2.8.12.2 without I jumping into so much hoops.
```

Setting up cmake (2.8.12.2-0ubuntu3) ...
username@www:~/software/ridl/build$ cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
username@www:~/software/ridl/build$
```

Can you provide a version where it's compatible with aforementioned version?

**Comment by StephanvanSchaik** [comment]
I have lowered the required version for CMake in ed8fa6ac84d2328d7696a6249ab72044026612bb. Could you check if it builds now?

**Comment by abrahamdsl** [comment]
Oh hello dear, only now did I see this update. I am going to check later. Thanks.

**Comment by abrahamdsl** [comment]
Hi, I confirm it now works:  Issue resolved. Thanks!
