### ISSUE TITLE
Modified spidermonkey binary links broken

### ISSUE THREAD

**Issue by jfoote** [vusec/ridl#29]
Just a heads up: the links to the [modified spidermonkey binary](https://www.cs.vu.nl/~herbertb/download/ridlers/files/js-shell.tar.gz) in the [RIDL.js](https://github.com/vusec/ridl/tree/master/pocs/js) README and download.sh seem to be broken.

**Comment by noopwafel** [comment]
Thanks. Probably fallout from reorganization of vusec downloads in general; I pinged people.

**Comment by pit-fr** [comment]
Fixed
