### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by deepdad** [vusec/ridl#5]
I couldn't get it to compile out of the box on MacOS Mojave and try on a VirtualBox Ubuntu 18 with CMake.
Please make a MacOSX binary available on mdsattacks.com
I will chase these
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xft_INCLUDE_PATH (ADVANCED)
   used as include directory in directory /home/ecommerce/Downloads/ridl-master
   used as include directory in directory /home/ecommerce/Downloads/ridl-master
   used as include directory in directory /home/ecommerce/Downloads/ridl-master
X11_Xft_LIB (ADVANCED)
    linked by target "mdstool" in directory /home/ecommerce/Downloads/ridl-master
X11_Xrender_INCLUDE_PATH (ADVANCED)
   used as include directory in directory /home/ecommerce/Downloads/ridl-master
   used as include directory in directory /home/ecommerce/Downloads/ridl-master
   used as include directory in directory /home/ecommerce/Downloads/ridl-master
X11_Xrender_LIB (ADVANCED)
    linked by target "mdstool" in directory /home/ecommerce/Downloads/ridl-master

**Comment by deepdad** [comment]
Seems today's Ubuntu 18 kernel update on VBox crashes my iMac Pro with hyperthreading turned off. I hope it's one time only, first time this machine crashed in almost 18 months.

**Comment by StephanvanSchaik** [comment]
I will try to work on the Mac OS X port in the next few days, to give you an idea of what has to be changed:
 * Mac OS X needs a different back-end using GLFW (which uses Cocoa + OpenGL), and not X11.
 * Mac OS X does not really use sysfs like Linux for some of the information, but like all the BSDs uses `sysctl`.
 * The `cpuid` part of the code might have to be rewritten so it can actually query CPU information.

**Comment by deepdad** [comment]
if it relies on cpuid, will it be correct when you turn off hyper-threading like Apple advises?
why doesn't it do an actual test like described in your paper?

**Comment by StephanvanSchaik** [comment]
Not all information comes from `cpuid`, such as whether your CPU has SMT enabled or disabled. This is why the tool tries to query this information from known APIs that the OS provides.

The tool doesn't use any of our tests because:
 1) Intel hasn't given us the green light yet for this.
 2) Mac OS X lacks an API to set explicit processor affinity to actually run the tests using SMT.

**Comment by StephanvanSchaik** [comment]
508d549341d785afc59681ed3f219ef72437d637 adds support for Mac OS X.
