### ISSUE TITLE
The tool has high CPU usage on Windows

### ISSUE THREAD

**Issue by rpremuz** [vusec/ridl#8]
I tested mdstool-win64.exe on a machine with **Intel i5-4210 CPU** and **4 GiB RAM** running **MS Windows 10 Pro. 64-bit v. 1703** and noticed the tool is causing constant high CPU usage of about 20%:

![CPU_usage](https://user-images.githubusercontent.com/5261871/57791980-4624b800-773e-11e9-8727-85680faee8f3.png)

It seems the tool is constantly doing something. This is strange as it should just collect some info from the system, display that info in the GUI and than be idle until closed.

**Comment by StephanvanSchaik** [comment]
This has been fixed in 8a3a2b5. Thanks!
